name: Deploy Angular Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --prod

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate version
        id: version
        run: echo "::set-output name=version::$(date +%s)" >>$GITHUB_ENV

      - name: Build docker image
        run: |
          docker build --no-cache -t basith7618/psyq-angular-app .
          # docker tag basith7618/psyq-angular-app:latest basith7618/psyq-angular-app:$(date +%s)

      - name: Publish image to dockerhub
        run: |
          docker push basith7618/psyq-angular-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: docker system prune -f

      - name: Create network
        run: docker network create app-network || true

      - name: Pull image from dockerhub
        run: docker pull basith7618/psyq-angular-app:latest

      - name: Delete old container
        run: docker rm -f psyq-angular-app-container || true

      - name: Run docker container
        run: |
          docker run -d -p 80:80 -p 443:443 --name psyq-angular-app-container --restart unless-stopped --network app-network basith7618/psyq-angular-app:latest


      - name: Debug container
        run: |
          echo "Container logs:"
          docker logs psyq-angular-app-container-container
          echo "Container status:"
          docker ps -a